spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/membermgmtdb
    username: root
    password: Arjun@1994
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8989/eureka			